<?php

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function lccc_athletics_player_profile_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function lccc_athletics_player_profile_add_meta_box() {
	add_meta_box(
		'lccc_athletics_player_profile-lccc-athletics-player-profile',
		__( 'LCCC Athletics Player Profile', 'lccc_athletics_player_profile' ),
		'lccc_athletics_player_profile_html',
		'lccc_player',
		'advanced',
		'core'
	);
}
add_action( 'add_meta_boxes', 'lccc_athletics_player_profile_add_meta_box' );



function lccc_athletics_player_profile_html( $post) {
	wp_nonce_field( '_lccc_athletics_player_profile_nonce', 'lccc_athletics_player_profile_nonce' );
?>

<script type="text/javascript">
	jQuery(function() {
  // Get the form fields and hidden div
  var checkbox = jQuery("#trigger");
		var coedcheckbox = jQuery("#coed_trigger");
  var hidden = jQuery("#hidden_fields");
		var hiddencoedfield = jQuery("#coed-hidden_fields");

  // Hide the fields.
  // Use JS to do this in case the user doesn't have JS
  // enabled.

		//hidden.hide();

  // Setup an event listener for when the state of the
  // checkbox changes.
  checkbox.change(function() {
    // Check to see if the checkbox is checked.
    // If it is, show the fields and populate the input.
    // If not, hide the fields.
    if (checkbox.is(':checked')) {
      // Show the hidden fields.
      hidden.toggle();

    } else {
      // Make sure that the hidden fields are indeed
      // hidden.
      hidden.hide();

      // You may also want to clear the value of the
      // hidden fields here. Just in case somebody
      // shows the fields, enters data to them and then
      // unticks the checkbox.
      //
      // This would do the job:
      //
      // $("#hidden_field").val("");
    }
  });
		coedcheckbox.change(function() {
    // Check to see if the checkbox is checked.
    // If it is, show the fields and populate the input.
    // If not, hide the fields.
    if (coedcheckbox.is(':checked')) {
      // Show the hidden fields.
      hiddencoedfield.toggle();

    } else {
      // Make sure that the hidden fields are indeed
      // hidden.
      hiddencoedfield.hide();

      // You may also want to clear the value of the
      // hidden fields here. Just in case somebody
      // shows the fields, enters data to them and then
      // unticks the checkbox.
      //
      // This would do the job:
      //
      // $("#hidden_field").val("");
    }
  });
});
	jQuery(document).ready(function () {
				toggleFields(); //call this first so we start out with the correct visibility depending on the selected form values
    //this will call our toggleFields function every time the selection value of our underAge field changes
    jQuery("#lccc_athletics_player_profile_sport").change(function () {
 					toggleFields();
    });
});
	//this toggles the visibility of our parent permission fields depending on the current selected value of the underAge field
function toggleFields() {

 	switch (jQuery("#lccc_athletics_player_profile_sport").val()){
			case 'Baseball':
					hideAll();
					jQuery("#baseball").show();
					jQuery("#secondary-postion-trigger").show();
			break;

			case 'Basketball':
					hideAll();
					jQuery("#basketball").show();
					jQuery("#secondary-postion-trigger").show();
			break;

			case 'Cross Country':
					hideAll();
					jQuery("#secondary-postion-trigger").hide();
			break;

		 case 'Fastpitch Softball':
					hideAll();
					jQuery("#fastpitch-softball").show();
					jQuery("#secondary-postion-trigger").show();
			break;

			case 'Soccer':
					hideAll();
					jQuery("#soccer").show();
					jQuery("#secondary-postion-trigger").show();
		 break;

			case 'Volleyball':
					hideAll();
					jQuery("#volleyball").show();
					jQuery("#secondary-postion-trigger").show();
				break;

			default:
				hideAll();
				jQuery("#secondary-postion-trigger").hide();
		}

}
				function hideAll(){
							jQuery("#basketball").hide();
							jQuery("#baseball").hide();
							jQuery("#fastpitch-softball").hide();
							jQuery("#soccer").hide();
							jQuery("#volleyball").hide();
		}
	</script>

	<p>This meta box is for the player profile including Height, Position, Hometown, High School and Year in School.</p>

<p>
		<label for="lccc_athletics_player_profile_jersey_number"><?php _e( 'Jersey Number', 'lccc_athletics_player_profile' ); ?></label><br>
		<input type="text" name="lccc_athletics_player_profile_jersey_number" id="lccc_athletics_player_profile_jersey_number" value="<?php echo lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_jersey_number' ); ?>">
	</p>
<p>
		<label for="lccc_athletics_player_profile_height"><?php _e( 'Height', 'lccc_athletics_player_profile' ); ?></label><br>
		<input type="text" name="lccc_athletics_player_profile_height" id="lccc_athletics_player_profile_height" value="<?php echo lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_height' ); ?>">
	</p>
<p>
		<label for="lccc_athletics_player_profile_sport"><?php _e( 'Sport', 'lccc_athletics_player_profile' ); ?></label><br>
		<select name="lccc_athletics_player_profile_sport" id="lccc_athletics_player_profile_sport">
			<?php
				$sports = array(' ','Baseball','Basketball', 'Cross Country' ,'Fastpitch Softball','Soccer','Volleyball');
				foreach ($sports as $sport){
						$selectedsport = esc_attr( lccc_athletics_player_profile_get_meta ('lccc_athletics_player_profile_sport') );
					echo '<option value="' . $sport . '" id="' . $sport . '"', $selectedsport == $sport ? ' selected="selected"' : '', '>', $sport, '</option>';
				}
	?>
		</select>
</p>

<div id="baseball">
		<label for="lccc_athletics_player_profile_position_baseball"><?php _e( 'Position', 'lccc_athletics_player_profile' ); ?></label><br>
		<select name="lccc_athletics_player_profile_position_baseball" id="lccc_athletics_player_profile_position_baseball">
			<?php
				$baseballpositions = array(' ','UTILITY', 'INF','OF','P','C','1B','2B','3B','SS');
				foreach ($baseballpositions as $baseballposition){

					$selectedbaseball = esc_attr( lccc_athletics_player_profile_get_meta ('lccc_athletics_player_profile_position_baseball') );

					echo '<option value="' . $baseballposition . '" id="' . $baseballposition . '"', $selectedbaseball == $baseballposition ? ' selected="selected"' : '', '>', $baseballposition, '</option>';
				}
	?>
		</select>
</div>
<div id="basketball">
		<label for="lccc_athletics_player_profile_position_basketball"><?php _e( 'Position', 'lccc_athletics_player_profile' ); ?></label><br>
		<select name="lccc_athletics_player_profile_position_basketball" id="lccc_athletics_player_profile_position_basketball">
			<?php
				$basketballpositions = array(' ','Guard','Forward','Center');
				foreach ($basketballpositions as $basketballposition){

					$selectedbasketball = esc_attr( lccc_athletics_player_profile_get_meta ('lccc_athletics_player_profile_position_basketball') );

					echo '<option value="' . $basketballposition . '" id="' . $basketballposition . '"', $selectedbasketball == $basketballposition ? ' selected="selected"' : '', '>', $basketballposition, '</option>';
				}
	?>
		</select>
</div>
<div id="fastpitch-softball">
		<label for="lccc_athletics_player_profile_position_softball"><?php _e( 'Position', 'lccc_athletics_player_profile' ); ?></label><br>
		<select name="lccc_athletics_player_profile_position_softball" id="lccc_athletics_player_profile_position_softball">
			<?php
				$softballpositions = array(' ','P','C','1B','2B','3B','SS','OF', 'IF', 'UTILITY');
				foreach ($softballpositions as $softballposition){

					$selectedsoftball = esc_attr( lccc_athletics_player_profile_get_meta ('lccc_athletics_player_profile_position_softball') );

					echo '<option value="' . $softballposition . '" id="' . $softballposition . '"', $selectedsoftball == $softballposition ? ' selected="selected"' : '', '>', $softballposition, '</option>';
				}
	?>
		</select>
</div>
<div id="soccer">
		<label for="lccc_athletics_player_profile_position_soccer"><?php _e( 'Position', 'lccc_athletics_player_profile' ); ?></label><br>
		<select name="lccc_athletics_player_profile_position_soccer" id="lccc_athletics_player_profile_position_soccer">
			<?php
				$soccerpositions = array(' ','Goalie','Defender','Midfielder','Forward');
				foreach ($soccerpositions as $soccerposition){

					$selectedsoccer = esc_attr( lccc_athletics_player_profile_get_meta ('lccc_athletics_player_profile_position_soccer') );

					echo '<option value="' . $soccerposition . '" id="' . $soccerposition . '"', $selectedsoccer == $soccerposition ? ' selected="selected"' : '', '>', $soccerposition, '</option>';
				}
	?>
		</select>
</div>
<div id="volleyball">
		<label for="lccc_athletics_player_profile_position_volleyball"><?php _e( 'Position', 'lccc_athletics_player_profile' ); ?></label><br>
		<select name="lccc_athletics_player_profile_position_volleyball" id="lccc_athletics_player_profile_position_volleyball">
			<?php
				$volleyballpositions = array(' ','DS','MH','OH','RS','S');
				foreach ($volleyballpositions as $volleyballposition){

					$selectedvolleyball = esc_attr( lccc_athletics_player_profile_get_meta ('lccc_athletics_player_profile_position_volleyball') );

					echo '<option value="' . $volleyballposition . '" id="' . $volleyballposition . '"', $selectedvolleyball == $volleyballposition ? ' selected="selected"' : '', '>', $volleyballposition, '</option>';
				}
	?>
		</select>
</div>
<br>
<div>
<?php
	$selectedseconaryposition = trim( esc_attr( lccc_athletics_player_profile_get_meta ('lccc_athletics_player_profile_secondary_position') ) );

	if ($selectedseconaryposition != ''){
		?>
					Has Secondary Position?: <input type="checkbox" id="trigger" name="second_position_question" checked>
</div>
<div id="hidden_fields">
	<?php
	}else{
	?>
				 <div id="secondary-postion-trigger"> Has Secondary Position?: <input type="checkbox" id="trigger" name="second_position_question"></div>
<br>
</div>
<div id="hidden_fields" style="display:none;">
	<?php
	}
?>

		<p>
		<label for="lccc_athletics_player_profile_secondary_position"><?php _e( 'Secondary Position', 'lccc_athletics_player_profile' ); ?></label>
				<select name="lccc_athletics_player_profile_secondary_position" id="lccc_athletics_player_profile_secondary_position">
								<?php
										$secondaryplayerpositions = array(' ','Baseball','-UTILITY','-INF','-OF','-P','-C','-1B','-2B','-3B','-SS','Basketball','-Guard','-Forward','-Center','Fastpitch Softball','-OF','-C','-P','-1B','-2B','-3B','-SS', 'IF', 'UTILITY','Soccer','-Goalie','-Defender','-Midfielder','-Forward','Volleyball','-DS','-MH','-OH','-RS','-S');
										foreach ($secondaryplayerpositions as $secondposition){
					echo '<option value="' . $secondposition . '" id="' . $secondposition . '"', $selectedseconaryposition == $secondposition ? ' selected="selected"' : '', '>', $secondposition, '</option>';
				}
									?>
				</select>
			</p>
</div>

<div>
<?php
	$selectedgender = trim(esc_attr( lccc_athletics_player_profile_get_meta ('lccc_athletics_player_profile_gender') ));
	if ($selectedgender != ''){
		?>
					 Co-Ed Team?: <input type="checkbox" id="coed_trigger" name="co_ed_question" checked>
</div>
<div id="coed-hidden_fields">
	<?php
	}else{
	?>
				 <div id="coed-trigger"> Co-Ed Team?: <input type="checkbox" id="coed_trigger" name="co_ed_question"></div>
	</div>
<div id="coed-hidden_fields" style="display:none;">
	<?php
	}
?>
<p>
		<label for="lccc_athletics_player_profile_gender"><?php _e( 'Gender', 'lccc_athletics_player_profile' ); ?></label><br>
		<select name="lccc_athletics_player_profile_gender" id="lccc_athletics_player_profile_gender">
			<?php
				$genders = array(' ','Male','Female');
				foreach ($genders as $gender){
					echo '<option value="' . $gender . '" id="' . $gender . '"', $selectedgender == $gender ? ' selected="selected"' : '', '>', $gender, '</option>';
				}
	?>
		</select>
</p>
	</div>
	<p>
		<label for="lccc_athletics_player_profile_year"><?php _e( 'Year', 'lccc_athletics_player_profile' ); ?></label><br>
		<input type="text" name="lccc_athletics_player_profile_year" id="lccc_athletics_player_profile_year" value="<?php echo lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_year' ); ?>">
	</p>	
	<p>
		<label for="lccc_athletics_player_profile_high_school"><?php _e( 'High School', 'lccc_athletics_player_profile' ); ?></label><br>
		<input type="text" name="lccc_athletics_player_profile_high_school" id="lccc_athletics_player_profile_high_school" value="<?php echo lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_high_school' ); ?>">
	</p>	
	<p>
		<label for="lccc_athletics_player_profile_hometown"><?php _e( 'Hometown', 'lccc_athletics_player_profile' ); ?></label><br>
		<input type="text" name="lccc_athletics_player_profile_hometown" id="lccc_athletics_player_profile_hometown" value="<?php echo lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_hometown' ); ?>">
	</p>
	<p>
		<label for="lccc_athletics_player_profile_acadmajor"><?php _e( 'Academic Major', 'lccc_athletics_player_profile' ); ?></label><br>
		<input type="text" name="lccc_athletics_player_profile_acadmajor" id="lccc_athletics_player_profile_acadmajor" value="<?php echo lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_acadmajor' ); ?>">
	</p>
	<p>
		<label for="lccc_athletics_player_profile_parents"><?php _e( 'Parent Names', 'lccc_athletics_player_profile' ); ?></label><br>
		<input type="text" name="lccc_athletics_player_profile_parents" id="lccc_athletics_player_profile_parents" value="<?php echo lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_parents' ); ?>">
	</p>

<?php
}

function lccc_athletics_player_profile_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['lccc_athletics_player_profile_nonce'] ) || ! wp_verify_nonce( $_POST['lccc_athletics_player_profile_nonce'], '_lccc_athletics_player_profile_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

		if ( isset( $_POST['lccc_athletics_player_profile_jersey_number'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_jersey_number', esc_attr( $_POST['lccc_athletics_player_profile_jersey_number'] ) );

	if ( isset( $_POST['lccc_athletics_player_profile_height'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_height', esc_attr( $_POST['lccc_athletics_player_profile_height'] ) );

	if ( isset( $_POST['lccc_athletics_player_profile_sport'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_sport', esc_attr( $_POST['lccc_athletics_player_profile_sport'] ) );

	if ( isset( $_POST['lccc_athletics_player_profile_position_baseball'] ) )
	{
		update_post_meta( $post_id, 'lccc_athletics_player_profile_position_baseball', esc_attr( $_POST['lccc_athletics_player_profile_position_baseball'] ) );

		}

	if ( isset( $_POST['lccc_athletics_player_profile_position_basketball'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_position_basketball', esc_attr( $_POST['lccc_athletics_player_profile_position_basketball'] ) );

	if ( isset( $_POST['lccc_athletics_player_profile_position_softball'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_position_softball', esc_attr( $_POST['lccc_athletics_player_profile_position_softball'] ) );

	if ( isset( $_POST['lccc_athletics_player_profile_position_soccer'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_position_soccer', esc_attr( $_POST['lccc_athletics_player_profile_position_soccer'] ) );

	if ( isset( $_POST['lccc_athletics_player_profile_position_volleyball'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_position_volleyball', esc_attr( $_POST['lccc_athletics_player_profile_position_volleyball'] ) );


	if ( isset( $_POST['second_position_question'] ) ){
		if ( isset( $_POST['lccc_athletics_player_profile_secondary_position'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_secondary_position', esc_attr( $_POST['lccc_athletics_player_profile_secondary_position'] ) );
		} else {
			update_post_meta( $post_id, 'lccc_athletics_player_profile_secondary_position', esc_attr('') );
	}

	if ( isset( $_POST['co_ed_question'] ) ){
		if ( isset( $_POST['lccc_athletics_player_profile_gender'] ) )
				update_post_meta( $post_id, 'lccc_athletics_player_profile_gender', esc_attr( $_POST['lccc_athletics_player_profile_gender'] ) );
		}else{
				update_post_meta( $post_id, 'lccc_athletics_player_profile_gender', esc_attr('') );
	}

	// Year - Academic Designation (Freshman, Sophomore, Junior, Senior)
	if ( isset( $_POST['lccc_athletics_player_profile_year'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_year', esc_attr( $_POST['lccc_athletics_player_profile_year'] ) );

	// High School

	if ( isset( $_POST['lccc_athletics_player_profile_high_school'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_high_school', esc_attr( $_POST['lccc_athletics_player_profile_high_school'] ) );
	
	// Hometown
	
	if ( isset( $_POST['lccc_athletics_player_profile_hometown'] ) )
		update_post_meta( $post_id, 'lccc_athletics_player_profile_hometown', esc_attr( $_POST['lccc_athletics_player_profile_hometown'] ) );

	// Academic Major lccc_athletics_player_profile_acadmajor

	if ( isset( $_POST['lccc_athletics_player_profile_acadmajor'] ) )
	update_post_meta( $post_id, 'lccc_athletics_player_profile_acadmajor', esc_attr( $_POST['lccc_athletics_player_profile_acadmajor'] ) );


	// Parents Names lccc_athletics_player_profile_parents

	if ( isset( $_POST['lccc_athletics_player_profile_parents'] ) )
	update_post_meta( $post_id, 'lccc_athletics_player_profile_parents', esc_attr( $_POST['lccc_athletics_player_profile_parents'] ) );


	}
add_action( 'save_post', 'lccc_athletics_player_profile_save' );

/*
	Usage: lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_height' )
	Usage: lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_position' )
	Usage: lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_secondary_position' )
	Usage: lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_year' )
	Usage: lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_height' )
	Usage: lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_high_school' )
	Usage: lccc_athletics_player_profile_get_meta( 'lccc_athletics_player_profile_hometown' )
*/


?>